"""Generate Rust test vectors from the Python reference implementation.

Run with the pyatv venv:
    /Users/corvofeng/GitRepo/pyatv/.venv/bin/python scripts/gen_fixtures.py

Writes generated test files into crates/atv-core/tests/.
"""

import binascii
import hashlib
import os
import sys
import uuid

PYATV_DIR = os.environ.get("PYATV_DIR", "/Users/corvofeng/GitRepo/pyatv")
sys.path.insert(0, PYATV_DIR)

import fake_atv  # noqa: E402
from srptools import SRPContext, SRPClientSession, SRPServerSession, constants  # noqa: E402

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "crates", "atv-core", "tests")


def rust_str(s: str) -> str:
    out = s.replace("\\", "\\\\").replace('"', '\\"')
    out = out.replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")
    return f'"{out}"'


def emit(v) -> str:
    if v is None:
        return "Value::Null"
    if isinstance(v, bool):
        return f"Value::Bool({str(v).lower()})"
    if isinstance(v, uuid.UUID):
        return f'u("{v.hex}")'
    if isinstance(v, int):
        return f"Value::Int({v}u64)"
    if isinstance(v, float):
        return f"Value::Double({v!r})"
    if isinstance(v, str):
        return f"Value::str({rust_str(v)})"
    if isinstance(v, bytes):
        return f'b("{v.hex()}")'
    if isinstance(v, list):
        return "arr(vec![" + ", ".join(emit(x) for x in v) + "])"
    if isinstance(v, dict):
        return "dct(vec![" + ", ".join(f"({emit(k)}, {emit(val)})" for k, val in v.items()) + "])"
    raise TypeError(type(v))


OPACK_CASES = {
    "none": None,
    "bools": [True, False],
    "small_ints": [0, 1, 0x27],
    "int_boundaries": [0x28, 0xFF, 0x100, 0xFFFF, 0x10000, 0xFFFFFFFF, 0x100000000, 0xFFFFFFFFFFFFFFFF],
    "floats": [0.5, -1.25, 3.141592653589793, 1e300],
    "strings": ["", "a", "x" * 0x20, "y" * 0x21, "z" * 0xFF, "w" * 0x100, "遥控器🔥", "quote\"back\\slash"],
    "bytes": [b"", b"\x00", bytes(range(0x20)), bytes(range(0x21)), bytes(range(256)) * 2],
    "uuid": uuid.UUID("5D797FD3-3538-427E-A47B-A32FC6CF3A6A"),
    "array_simple": [1, "two", b"\x03", None, True, 2.5],
    "array_endless": list(range(20)),
    "nested": {"a": [1, {"b": [2, {"c": None}]}, ("not-a-tuple")], "d": {"e": [{"f": 1.5}]},},
    "dict_simple": {"_i": "_hidC", "_t": 2, "_c": {"_hidC": 1, "_hBtS": 1}, "_x": 12345},
    "dict_endless": {f"key{i:02d}": i * 7 for i in range(16)},
    # Object reference: the same >1-byte packed value appears twice; the
    # second occurrence must encode as a reference marker.
    "object_ref_short": {"k1": "repeated-string-value", "k2": "repeated-string-value"},
    "object_ref_nested": [["shared bytes object"] * 3, {"x": "shared bytes object"}],
    # Push the object table past 0x21 entries so the 0xC1 (1-byte index)
    # reference form is exercised: 40 distinct strings, then repeat the first.
    "object_ref_long_index": {
        **{f"k{i:02d}": f"distinct-value-{i:02d}" for i in range(40)},
        "repeat": "distinct-value-00",
    },
}


def gen_opack():
    lines = [
        "// Generated by scripts/gen_fixtures.py -- do not edit.",
        "// Each case asserts byte-identical OPACK output vs fake_atv.opack_pack,",
        "// plus unpack() returning an equal value.",
        "#![allow(clippy::all)]",
        "",
        "use atv_core::opack::{pack, unpack, Value};",
        "",
        "fn b(hex: &str) -> Value { Value::Bytes(hex::decode(hex).unwrap()) }",
        "fn u(hex: &str) -> Value { Value::Uuid(hex::decode(hex).unwrap().try_into().unwrap()) }",
        "fn arr(xs: Vec<Value>) -> Value { Value::Array(xs) }",
        "fn dct(xs: Vec<(Value, Value)>) -> Value { Value::Dict(xs) }",
        "",
        "fn check(name: &str, value: Value, expected_hex: &str) {",
        "    let expected = hex::decode(expected_hex).unwrap();",
        "    let packed = pack(&value);",
        "    assert_eq!(packed, expected, \"pack mismatch for {name}\");",
        "    let (unpacked, remaining) = unpack(&expected).unwrap();",
        "    assert!(remaining.is_empty(), \"trailing bytes for {name}\");",
        "    assert_eq!(unpacked, value, \"unpack mismatch for {name}\");",
        "}",
        "",
    ]
    for name, value in OPACK_CASES.items():
        expected = fake_atv.opack_pack(value).hex()
        lines.append(f"#[test]")
        lines.append(f"fn opack_{name}() {{")
        lines.append(f"    check({rust_str(name)}, {emit(value)}, {rust_str(expected)});")
        lines.append("}")
        lines.append("")
    with open(os.path.join(OUT_DIR, "opack_vectors.rs"), "w") as f:
        f.write("\n".join(lines))
    print(f"wrote opack_vectors.rs ({len(OPACK_CASES)} cases)")


def gen_crypto():
    out_key = bytes(range(32))
    in_key = bytes(range(32, 64))
    bodies = (
        b'{"_i":"_hidC"}',
        fake_atv.opack_pack({"_i": "_hidC", "_t": 2, "_c": {"_hidC": 1, "_hBtS": 1}}),
        b"\x00" * 100,
    )
    headers = [bytes([8]) + (len(body) + 16).to_bytes(3, "big") for body in bodies]

    # Server->client direction (output key, counter nonces 0, 1, 2).
    cipher = fake_atv.CompanionCipher(out_key, in_key)
    out_cts = [cipher.encrypt(body, aad=header) for body, header in zip(bodies, headers)]
    # Client->server direction (input key, counter nonces 0, 1, 2).
    peer = fake_atv.CompanionCipher(in_key, in_key)
    in_cts = [peer.encrypt(body, aad=header) for body, header in zip(bodies, headers)]

    # Explicit 8-byte nonce (pair-setup style).
    ps_cipher = fake_atv.CompanionCipher(in_key, in_key, nonce_length=8)
    explicit_plain = fake_atv.write_tlv({1: b"client-id", 3: bytes(range(32))})
    explicit_ct = ps_cipher.encrypt(explicit_plain, nonce=b"PS-Msg05")

    hkdf_shared = bytes(range(64))
    hkdf_out = fake_atv.hkdf_expand("Pair-Verify-Encrypt-Salt", "Pair-Verify-Encrypt-Info", hkdf_shared)
    hkdf_out_empty_salt = fake_atv.hkdf_expand("", "ServerEncrypt-main", hkdf_shared)

    lines = [
        "// Generated by scripts/gen_fixtures.py -- do not edit.",
        "// CompanionCipher/HKDF vectors produced by fake_atv.py.",
        "#![allow(clippy::all)]",
        "",
        "use atv_core::crypto::{hkdf_expand, CompanionCipher};",
        "",
        f'const OUT_KEY: &str = "{out_key.hex()}";',
        f'const IN_KEY: &str = "{in_key.hex()}";',
        "",
        "fn new_cipher() -> CompanionCipher {",
        "    CompanionCipher::new(",
        "        &hex::decode(OUT_KEY).unwrap(),",
        "        &hex::decode(IN_KEY).unwrap(),",
        "        12,",
        "    ).unwrap()",
        "}",
        "",
        "#[test]",
        "fn cipher_counter_nonce_encrypt_matches_python() {",
        "    let mut cipher = new_cipher();",
    ]
    for i, (body, header, ct) in enumerate(zip(bodies, headers, out_cts)):
        lines += [
            f'    let body = hex::decode("{body.hex()}").unwrap();',
            f'    let header = hex::decode("{header.hex()}").unwrap();',
            f'    let expected = hex::decode("{ct.hex()}").unwrap();',
            f'    assert_eq!(cipher.encrypt(&body, Some(&header), None).unwrap(), expected, "frame {i}");',
        ]
    lines += [
        "}",
        "",
        "#[test]",
        "fn cipher_counter_nonce_decrypt_matches_python() {",
        "    let mut cipher = new_cipher();",
    ]
    for i, (body, header, ct) in enumerate(zip(bodies, headers, in_cts)):
        lines += [
            f'    let body = hex::decode("{body.hex()}").unwrap();',
            f'    let header = hex::decode("{header.hex()}").unwrap();',
            f'    let encrypted = hex::decode("{ct.hex()}").unwrap();',
            f'    assert_eq!(cipher.decrypt(&encrypted, Some(&header), None).unwrap(), body, "frame {i}");',
        ]
    lines += [
        "}",
        "",
        "#[test]",
        "fn cipher_explicit_nonce_matches_python() {",
        "    let mut cipher = CompanionCipher::new(",
        "        &hex::decode(IN_KEY).unwrap(),",
        "        &hex::decode(IN_KEY).unwrap(),",
        "        8,",
        "    ).unwrap();",
        f'    let plain = hex::decode("{explicit_plain.hex()}").unwrap();',
        f'    let expected = hex::decode("{explicit_ct.hex()}").unwrap();',
        '    assert_eq!(cipher.encrypt(&plain, None, Some(b"PS-Msg05")).unwrap(), expected);',
        '    assert_eq!(cipher.decrypt(&expected, None, Some(b"PS-Msg05")).unwrap(), plain);',
        "}",
        "",
        "#[test]",
        "fn hkdf_matches_python() {",
        f'    let shared = hex::decode("{hkdf_shared.hex()}").unwrap();',
        "    assert_eq!(",
        '        hkdf_expand("Pair-Verify-Encrypt-Salt", "Pair-Verify-Encrypt-Info", &shared).to_vec(),',
        f'        hex::decode("{hkdf_out.hex()}").unwrap(),',
        "    );",
        "    assert_eq!(",
        '        hkdf_expand("", "ServerEncrypt-main", &shared).to_vec(),',
        f'        hex::decode("{hkdf_out_empty_salt.hex()}").unwrap(),',
        "    );",
        "}",
        "",
    ]
    with open(os.path.join(OUT_DIR, "crypto_vectors.rs"), "w") as f:
        f.write("\n".join(lines))
    print("wrote crypto_vectors.rs")


def gen_srp():
    pin = 1111
    salt = bytes.fromhex("00112233445566778899aabbccddeeff")
    client_private = bytes(range(1, 33))  # a, fixed for reproducibility

    def make_ctx(password=None):
        return SRPContext(
            "Pair-Setup",
            password,
            prime=constants.PRIME_3072,
            generator=constants.PRIME_3072_GEN,
            hash_func=hashlib.sha512,
            bits_salt=128,
        )

    # Server side, exactly like fake_atv._reset_pairing_session but with a
    # fixed salt.
    ctx = make_ctx(str(pin))
    x = ctx.get_common_password_hash(salt)
    verifier = ctx.get_common_password_verifier(x)
    server_ctx = make_ctx()
    server = SRPServerSession(server_ctx, "%x" % verifier, binascii.hexlify(32 * b"\xaa").decode())
    server_salt_hex = binascii.hexlify(salt).decode()

    # Client side with fixed private a.
    client_ctx = make_ctx(str(pin))
    client = SRPClientSession(client_ctx, binascii.hexlify(client_private).decode())
    client.process(server.public, server_salt_hex)
    client_public = binascii.unhexlify(client.public)
    client_proof = binascii.unhexlify(client.key_proof)

    server.process(client.public, server_salt_hex)
    assert server.verify_proof(binascii.hexlify(client_proof))
    server_proof_hash = binascii.unhexlify(server.key_proof_hash)
    session_key = binascii.unhexlify(server.key)

    # The client also verifies the server's proof hash (pyatv step2).
    assert client.verify_proof(binascii.hexlify(server_proof_hash))

    lines = [
        "// Generated by scripts/gen_fixtures.py -- do not edit.",
        "// SRP pair-setup vector computed with srptools (Apple variant:",
        "// 3072-bit group, SHA-512, 128-bit salt, server private = 32 x 0xaa).",
        "#![allow(clippy::all)]",
        "",
        "use atv_core::srp::SrpServer;",
        "",
        "#[test]",
        "fn srp_pair_setup_matches_srptools() {",
        f"    let salt = hex::decode(\"{salt.hex()}\").unwrap();",
        "    let mut server = SrpServer::with_salt(1111, &[0xaa; 32], &salt);",
        f"    let expected_b = hex::decode(\"{binascii.unhexlify(server.public).hex()}\").unwrap();",
        "    assert_eq!(server.public_key(), expected_b, \"server public key B\");",
        f"    let client_public = hex::decode(\"{client_public.hex()}\").unwrap();",
        "    server.process(&client_public).unwrap();",
        f"    let client_proof = hex::decode(\"{client_proof.hex()}\").unwrap();",
        "    assert!(server.verify_proof(&client_proof), \"client proof M1\");",
        "    assert!(!server.verify_proof(&[0u8; 64]), \"wrong proof must fail\");",
        f"    let expected_proof_hash = hex::decode(\"{server_proof_hash.hex()}\").unwrap();",
        "    assert_eq!(server.key_proof_hash().unwrap(), expected_proof_hash, \"H(A|M|K)\");",
        f"    let expected_key = hex::decode(\"{session_key.hex()}\").unwrap();",
        "    assert_eq!(server.session_key().unwrap(), &expected_key[..], \"session key K\");",
        "}",
        "",
    ]
    with open(os.path.join(OUT_DIR, "srp_vectors.rs"), "w") as f:
        f.write("\n".join(lines))
    print("wrote srp_vectors.rs")


if __name__ == "__main__":
    gen_opack()
    gen_crypto()
    gen_srp()
